create or replace stage  aws_stage
url='s3://bucketsnowflakes3'

list @aws_stage

copy into orders
from @aws_stage
file_format=(type=csv field_delimiter=','skip_header=1)
pattern= 'OrdersDetails'

select * from orders

create or replace table orders_caching (
ORDER_ID VARCHAR(20),
AMOUNT NUMBER(38,0),
PROFIT NUMBER(38,0),
QUNATITY NUMBER(38,0),
CATEGORY VARCHAR(20),
SUBCATEGORY VARCHAR(20),
DATE DATE
)


// HOW TO COPY DUMMY VALUES FROM OTHER TABLE FORMAT

INSERT INTO ORDERS_CACHING
SELECT 
T1.ORDER_ID,
T1.AMOUNT ,
T1.PROFIT ,
T1.QUNATITY ,
T1.CATEGORY ,
T1.SUBCATEGORY ,
DATE (DATE (UNIFORM (1500000000,1700000000, (RANDOM())))
)
FROM ORDERS T1
CROSS JOIN (SELECT * FROM ORDERS) T2
CROSS JOIN (SELECT TOP 100* FROM ORDERS) T3

SELECT * FROM ORDERS_CACHING WHERE DATE='2020-07-09'

//ADDING CLUSTER KEY AND COMPARING THE RESULT

ALATER TABLE ORDERS_CACHING BY CLUSTER(DATE)

SELECT *FROM ORDERS_CACHING WHERE DATE ='2020-01-05'
